name: Bosssports Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Python kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Gereksinimler
        run: pip install -r requirements.txt

      - name: Playwright browser indir
        run: playwright install chromium

      - name: Script çalıştır
        run: python pygoals.py

      - name: JSON commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add bosssports.json
          git commit -m "auto update bosssports" || echo "Değişiklik yok"
          git push
