name: bosssports update

on:
  workflow_dispatch:   # MANUEL ÇALIŞTIRMA
  schedule:
    - cron: "*/5 * * * *"   # 5 dakikada 1 (istersen değiştir)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ❗ push hatasını önler

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        run: |
          python pygoals.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add bosssports.json
          git commit -m "auto update bosssports" || echo "No changes"

          git pull origin main --rebase
          git push
